ci: Enable tests for iOS on GHA
These were left out of the intial migration for some reason so this just
transfers over those tests

Signed-off-by: Eli Uriegas <eliuriegasfb.com>

ghstack-source-id: ac72713fbd58dc1654072b935141831ff9a8fcdd
Pull Request resolved: https://github.com/pytorch/pytorch/pull/71644

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

diff --git a/.github/templates/ios_ci_workflow.yml.j2 b/.github/templates/ios_ci_workflow.yml.j2
--- a/.github/templates/ios_ci_workflow.yml.j2
+++ b/.github/templates/ios_ci_workflow.yml.j2
@@ -38,23 +38,58 @@ env:
   BUILD_ENVIRONMENT: !{{ build_environment }}
   IN_CI: 1
   IS_GHA: 1
+  IOS_PLATFORM: !{{ ios_platform }}
+  IOS_ARCH: !{{ ios_arch }}
 !{{ common.set_xcode_version(xcode_version) }}
 
 jobs:
 {% block build +%}
   build:
+    # NOTE: These builds will not run successfully without running on `pytorch/pytorch` due to the limitations
+    #       of accessing secrets from forked pull requests and IOS' dependency on secrets for their build/test
+    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
     runs-on: macos-10.15
     timeout-minutes: !{{ common.timeout_minutes }}
     env:
       JOB_BASE_NAME: !{{ build_environment }}-build
       IOS_CERT_KEY_2022: ${{ secrets.IOS_CERT_KEY_2022 }}
       IOS_SIGN_KEY_2022: ${{ secrets.IOS_SIGN_KEY_2022 }}
+      IOS_DEV_TEAM_ID: ${{ secrets.IOS_DEV_TEAM_ID }}
       PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
     steps:
       - name: print labels
         run: echo "${PR_LABELS}"
       !{{ common.checkout() }}
+      - name: Setup ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: 2.6
+          bundler-cache: true
+          working-directory: ios/TestApp/
+      # NOTE: the setup-miniconda action takes it upon itself to overwrite the PATH with whatever it thinks is correct
+      #       meaning that things like setup-ruby won't actually get setup correctly if run after setup-miniconda
       !{{ common.setup_miniconda("3.8") }}
+      - name: Populate CI build options
+        run: |
+          # Most builds use the lite interpreter, if certain builds shouldn't
+          # build the lite interpreter this env variable should get over-written
+          # in the following case statement
+          echo "BUILD_LITE_INTERPRETER=1" >> "${GITHUB_ENV}"
+
+          case ${BUILD_ENVIRONMENT} in
+            *metal*)
+              echo "USE_PYTORCH_METAL=1" >> "${GITHUB_ENV}"
+              ;;
+            *full_jit*)
+              echo "BUILD_LITE_INTERPRETER=0" >> "${GITHUB_ENV}"
+              ;;
+            *custom*)
+              echo "SELECTED_OP_LIST=${GITHUB_WORKSPACE}/ios/TestApp/custom_build/mobilenetv2.yaml" >> "${GITHUB_ENV}"
+              ;;
+            *coreml*)
+              echo "USE_COREML_DELEGATE=1" >> "${GITHUB_ENV}"
+              ;;
+          esac
       - name: Install ios / conda Dependencies
         run: |
           # Install dependencies
@@ -66,7 +101,7 @@ jobs:
           set -x
           cd ios/TestApp
           # install fastlane
-          sudo gem install bundler && bundle install
+          gem install bundler && bundle install
           # install certificates
           echo "${IOS_CERT_KEY_2022}" >> cert.txt
           base64 --decode cert.txt -o Certificates.p12
@@ -87,6 +122,52 @@ jobs:
           python -VV
           export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname "$(which conda)")/../"}
           scripts/build_ios.sh
+      - name: Run Build Test
+        run: |
+          PROFILE=PyTorch_CI_2022
+          # run the ruby build script
+          if ! [ -x "$(command -v xcodebuild)" ]; then
+            echo 'Error: xcodebuild is not installed.'
+            exit 1
+          fi
+          if [ "${IOS_PLATFORM}" != "SIMULATOR" ]; then
+            ruby scripts/xcode_build.rb -i build_ios/install -x ios/TestApp/TestApp.xcodeproj -p "${IOS_PLATFORM}" -c "${PROFILE}" -t "${IOS_DEV_TEAM_ID}"
+          else
+            ruby scripts/xcode_build.rb -i build_ios/install -x ios/TestApp/TestApp.xcodeproj -p "${IOS_PLATFORM}"
+          fi
+{%- if ios_platform == "SIMULATOR" %}
+      - name: Run Simulator Tests
+        run: |
+          pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
+          # generate models for differnet backends
+          cd "${GITHUB_WORKSPACE}/ios/TestApp/benchmark"
+          mkdir -p ../models
+          if [ "${USE_COREML_DELEGATE}" == 1 ]; then
+            pip install coremltools==5.0b5
+            pip install six==1.16.0
+            python coreml_backend.py
+          else
+            python trace_model.py
+          fi
+          if [ "${BUILD_LITE_INTERPRETER}" == 1 ]; then
+            echo "Setting up the TestApp for LiteInterpreter"
+            ruby setup.rb --lite 1
+          else
+            echo "Setting up the TestApp for Full JIT"
+            ruby setup.rb
+          fi
+          cd "${GITHUB_WORKSPACE}/ios/TestApp"
+          instruments -s -devices
+          if [ "${BUILD_LITE_INTERPRETER}" == 1 ]; then
+            if [ "${USE_COREML_DELEGATE}" == 1 ]; then
+              fastlane scan --only_testing TestAppTests/TestAppTests/testCoreML
+            else
+              fastlane scan --only_testing TestAppTests/TestAppTests/testLiteInterpreter
+            fi
+          else
+            fastlane scan --only_testing TestAppTests/TestAppTests/testFullJIT
+          fi
+{%- endif -%}
 {% endblock +%}
 
 !{{ common.concurrency(build_environment) }}
